<?xml version="1.0"?>
<package format="3">
  <name>perception</name>
  <version>0.1.0</version>
  <description>Perception embarquée et passerelle vers le mât.</description>
  <maintainer email="robot@ema-bot.local">EMA Bot</maintainer>
  <license>UNLICENSED</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <export><build_type>ament_python</build_type></export>
</package>